# Generated by Django 5.0.7 on 2024-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_autor_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default='No description', help_text='Ingrese una breve descripción de la categoría', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del autor', max_length=200),
        ),
    ]
