# Generated by Django 5.0.7 on 2024-07-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_descripcion_alter_autor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default='No description', help_text='Ingrese una breve descripción de la categoría', max_length=1000),
        ),
    ]
